[package]
publish = false
name = "cli"
description = "Actuate command-line interface and persistent sessions"
repository.workspace = true
homepage.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
[[bin]]
name = "actuate"
path = "src/main.rs"
[dependencies]
actuate.workspace = true
overlay.workspace = true
macos.workspace = true
serde_json.workspace = true
usage.workspace = true
serde.workspace = true
ios.workspace = true
android = { path = "../android", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
linux.workspace = true

[features]
default = ["idevice", "android"]
idevice = ["ios/physical"]
android = ["dep:android"]

[target.'cfg(target_os = "windows")'.dependencies]
windows = { path = "../windows" }
