[package]
publish = false
name = "cli"
version.workspace = true
edition.workspace = true
license.workspace = true
[[bin]]
name = "unimation"
path = "src/main.rs"
[dependencies]
unimation.workspace = true
macos.workspace = true
serde_json.workspace = true
usage.workspace = true
serde.workspace = true
ios.workspace = true
android = { path = "../android", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
linux.workspace = true

[features]
default = ["idevice", "android"]
idevice = ["ios/physical"]
android = ["dep:android"]
