[package]
publish = false
name = "overlay"
version.workspace = true
edition.workspace = true
license.workspace = true
[dependencies]
unimation.workspace = true
serde.workspace = true
serde_json.workspace = true
[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.4"
objc2-app-kit = {version="0.3.2",default-features=false,features=["std","NSApplication","NSRunningApplication","NSWindow","NSPanel","NSView","NSColor","NSBezierPath","NSGraphics","NSResponder","objc2-core-foundation"]}
objc2-foundation = {version="0.3.2",default-features=false,features=["std","NSTimer","NSDate","NSRunLoop","NSGeometry","NSObject","block2"]}
objc2-core-graphics = {version="0.3.2",default-features=false,features=["std","CGDirectDisplay"]}
block2 = "0.6.2"

[[bin]]
name = "unimation-overlay"
path = "src/main.rs"
