[package]
publish = false
name = "overlay"
version.workspace = true
edition.workspace = true
license.workspace = true
[dependencies]
unimation.workspace = true
serde.workspace = true
serde_json.workspace = true
[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.4"
objc2-app-kit = {version="0.3.2",default-features=false,features=["std","NSApplication","NSRunningApplication","NSWindow","NSPanel","NSView","NSColor","NSBezierPath","NSGraphics","NSGraphicsContext","NSShadow","NSResponder","libc","objc2-core-foundation"]}
objc2-foundation = {version="0.3.2",default-features=false,features=["std","NSTimer","NSDate","NSRunLoop","NSGeometry","NSObject","NSArray","NSString","block2"]}
objc2-core-graphics = {version="0.3.2",default-features=false,features=["std","CGDirectDisplay","CGWindow","CGGeometry"]}
libc = "0.2"
objc2-core-foundation = "0.3.2"
block2 = "0.6.2"

[[bin]]
name = "unimation-overlay"
path = "src/main.rs"

[target.'cfg(target_os = "macos")'.dependencies.objc2-application-services]
version = "0.3.2"
default-features = false
features = ["std", "AXUIElement", "AXError", "HIServices", "libc"]

[target.'cfg(target_os = "linux")'.dependencies]
x11rb = { version = "0.13.2", features = ["shape"] }

[target.'cfg(target_os = "windows")'.dependencies]
tiny-skia = { version = "0.11", default-features = false, features = ["std", "simd"] }
windows_api = { package = "windows", version = "0.62.2", features = ["Win32_Foundation", "Win32_Graphics_Gdi", "Win32_Graphics_Dwm", "Win32_UI_WindowsAndMessaging", "Win32_UI_HiDpi", "Win32_System_Com", "Win32_UI_Shell", "Win32_System_LibraryLoader"] }
