[package]
name = "unimation-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
[[bin]]
name = "unimation"
path = "src/main.rs"
[dependencies]
unimation-core.workspace = true
unimation-macos.workspace = true
serde_json.workspace = true
usage = { package = "usage-rs", version = "6.9.1", default-features = false, features = ["help", "diagnostics"] }
